<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true"  CodeFile="EditDeleteinfo.aspx.cs" Inherits="EditDeleteinfo" %>
 
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <script>
        function isDelete() {
            return confirm("Do you want to delete this row ?");
        }
    </script>
  
    <div style="padding: 10px; margin: 0px; width: 100%;">  
        <td class="td" style="width:800px"><h2>Below Datas Are Arranged In Terms Of AppointmentList</h2></td>
       <asp:GridView ID="GridView1" runat="server" AllowSorting="True" DataKeyNames = "id"  AutoGenerateColumns="False" BackColor="White" BorderColor="#DEDFDE" BorderStyle="None" BorderWidth="1px" CellPadding="4"  EnableModelValidation="True" ForeColor="Black" GridLines="Vertical" Height="16px"  Width="908px" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataSourceID="SqlDataSource1">
            <AlternatingRowStyle BackColor="White" />
            <Columns>
                
                <asp:BoundField DataField="firstname" HeaderText="FirstName" SortExpression="firstname" />
                <asp:BoundField DataField="lastname" HeaderText="LastName" SortExpression="lastname" />
                <asp:BoundField DataField="gender" HeaderText="Gender" SortExpression="gender" />
                <asp:BoundField DataField="problem" HeaderText="Problem" SortExpression="problem" />
                <asp:BoundField DataField="doctor" HeaderText="Doctor" SortExpression="doctor" />
                <asp:BoundField DataField="nationality" HeaderText="Nationality" SortExpression="nationality" />
 

        
        
            
            
                <asp:BoundField DataField="contact" HeaderText="contact" SortExpression="contact" />
 

        
        
            
            
            </Columns>
            <FooterStyle BackColor="#CCCC99" />
            <HeaderStyle BackColor="#6B696B" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#F7F7DE" ForeColor="Black" HorizontalAlign="Right" />
            <RowStyle BackColor="#F7F7DE" />
           </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ProjectConnectionString %>" SelectCommand="SELECT * FROM [app]" UpdateCommand="UPDATE [app] Set [firstname]=@firstname,[lastname]=@lastname,[gender]=@gender,[problem]=@problem,[doctor]=@doctor,[nationality]=@nationality,[contact]=@contact WHERE [id]=@id" DeleteCommand="DELETE from [app] WHERE [id]=@id" ></asp:SqlDataSource>
        <br />
        <br />
        <br />
        <td class="td" style="width:800px"><h2>Below Datas Are Arranged In Terms Of DoctorList</h2></td>
        <asp:GridView ID="GridView2" runat="server" DataSourceID="SqlDataSource2" AllowSorting="True" AutoGenerateColumns="False" BackColor="White" BorderColor="#DEDFDE" DataKeyNames = "id"  BorderStyle="None" BorderWidth="1px" CellPadding="4"  EnableModelValidation="True" ForeColor="Black" GridLines="Vertical" Height="37px" Data  Width="908px" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True"  >
            <AlternatingRowStyle BackColor="White" />
            <Columns>
                
                <asp:BoundField DataField="doctorsname" HeaderText="Doctor's Name" SortExpression="doctorsname" />
                <asp:BoundField DataField="qualification" HeaderText="Qualification" SortExpression="qualification" />
                <asp:BoundField DataField="department" HeaderText="Department" SortExpression="department" />
                <asp:BoundField DataField="specialization" HeaderText="Specialization" SortExpression="specialization" />
                <asp:BoundField DataField="contact" HeaderText="Contact" SortExpression="contact" />
                
                
              
        
            </Columns>
            <FooterStyle BackColor="#CCCC99" />
            <HeaderStyle BackColor="#6B696B" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#F7F7DE" ForeColor="Black" HorizontalAlign="Right" />
            <RowStyle BackColor="#F7F7DE" />
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:ProjectConnectionString %>" SelectCommand="SELECT * FROM [doctorinfo]" UpdateCommand="UPDATE [doctorinfo] Set [doctorsname]=@doctorsname,[qualification]=@qualification,[department]=@department,[specialization]=@specialization,[contact]=@contact WHERE [id]=@id" DeleteCommand="DELETE from [doctorinfo] WHERE [id]=@id"></asp:SqlDataSource>
        
        
    </div> 
       
</asp:Content>  



